name: Secret Scanning

on:
    push

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Scan code
              uses: trufflesecurity/trufflehog@main
              with:
                extra_args: --only-verified